server:
  port: 5005

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://root:XWXuOlJDITwjwXbzteVItSJNpyESKNdU@switchback.proxy.rlwy.net:39815/railway
    username: root
    password: XWXuOlJDITwjwXbzteVItSJNpyESKNdU

  rabbitmq:
    host: armadillo.rmq.cloudamqp.com
    port: 5672
    username: avhqyyix
    password: ghDX0t0EkLkCdj0-wcDgtm2Honpt9sDk
    virtual-host: avhqyyix

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://spring-cloud-netflix-eureka-production-cb25.up.railway.app/eureka/