version: "3.8"

services:

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  eurekaserver:
    image: govindkalal/salon-eurekaserver-yt:v1
    container_name: eurekaserver
    ports:
      - "8070:8070"
    restart: always

  gatewayserver:
    image: govindkalal/salon-gatewayserver-yt:v1
    container_name: gatewayserver
    ports:
      - "5000:5000"
    environment:
      SPRING_APPLICATION_NAME: gateway-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_CLOUD_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - eurekaserver
    restart: always

  user:
    image: govindkalal/salon-user-yt:v1
    container_name: user
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/user_yt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    depends_on:
      - mysqldb
      - eurekaserver
    restart: always

  booking:
    image: govindkalal/salon-booking-yt:v1
    container_name: booking
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/booking_yt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    depends_on:
      - mysqldb
      - eurekaserver
    restart: always

  category:
    image: govindkalal/salon-category-yt:v1
    container_name: category
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/category_yt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    depends_on:
      - mysqldb
      - eurekaserver
    restart: always

  payment:
    image: govindkalal/salon-payment-yt:v1
    container_name: payment
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/payment_yt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    depends_on:
      - mysqldb
      - eurekaserver
    restart: always

  salon:
    image: govindkalal/salon-yt:v1
    container_name: salon
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/salon_yt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    depends_on:
      - mysqldb
      - eurekaserver
    restart: always

  service-offering:
    image: govindkalal/salon-service-offering-yt:v1
    container_name: service-offering
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/service_yt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    depends_on:
      - mysqldb
      - eurekaserver
    restart: always

volumes:
  mysql_data: