CREATE DATABASE IF NOT EXISTS user_yt;
CREATE DATABASE IF NOT EXISTS booking_yt;
CREATE DATABASE IF NOT EXISTS category_yt;
CREATE DATABASE IF NOT EXISTS payment_yt;
CREATE DATABASE IF NOT EXISTS salon_yt;
CREATE DATABASE IF NOT EXISTS service_yt;