
server:
  port: 5001

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://root:XWXuOlJDITwjwXbzteVItSJNpyESKNdU@switchback.proxy.rlwy.net:39815/railway
    username: root
    password: XWXuOlJDITwjwXbzteVItSJNpyESKNdU

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://spring-cloud-netflix-eureka-production-cb25.up.railway.app/eureka/