

server:
  port: 5007


spring:
  application:
    name: notification-service




  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://root:XWXuOlJDITwjwXbzteVItSJNpyESKNdU@switchback.proxy.rlwy.net:39815/railway
    username: root
    password: XWXuOlJDITwjwXbzteVItSJNpyESKNdU

  rabbitmq:
    host: armadillo.rmq.cloudamqp.com
    port: 5672
    username: avhqyyix
    password: ghDX0t0EkLkCdj0-wcDgtm2Honpt9sDk
    virtual-host: avhqyyix


eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://spring-cloud-netflix-eureka-production-cb25.up.railway.app/eureka/